# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.passwd = QtWidgets.QTextEdit(self.centralwidget)
        self.passwd.setGeometry(QtCore.QRect(240, 0, 231, 41))
        self.passwd.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.passwd.setAutoFillBackground(True)
        self.passwd.setObjectName("passwd")
        self.generatebutton = QtWidgets.QPushButton(self.centralwidget)
        self.generatebutton.setGeometry(QtCore.QRect(270, 370, 151, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generatebutton.sizePolicy().hasHeightForWidth())
        self.generatebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generatebutton.setFont(font)
        self.generatebutton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.generatebutton.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border:solid;\n"
"border-width: 10px;\n"
"border-radius: 20px")
        self.generatebutton.setObjectName("generatebutton")
        self.letterscheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.letterscheckbox.setGeometry(QtCore.QRect(100, 480, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.letterscheckbox.setFont(font)
        self.letterscheckbox.setObjectName("letterscheckbox")
        self.numbercheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.numbercheckbox.setGeometry(QtCore.QRect(100, 430, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.numbercheckbox.setFont(font)
        self.numbercheckbox.setObjectName("numbercheckbox")
        self.generate = QtWidgets.QLabel(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(90, 380, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.generate.setFont(font)
        self.generate.setObjectName("generate")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 50, 801, 311))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("kartinka-iz-multfilma-shrek-1.500x500.jpg"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(230, 510, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setObjectName("result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.passwd.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:400;\">Генератор пароля</span></p></body></html>"))
        self.generatebutton.setText(_translate("MainWindow", "Згенерувати"))
        self.letterscheckbox.setText(_translate("MainWindow", "Букви:"))
        self.numbercheckbox.setText(_translate("MainWindow", "Цифри:"))
        self.generate.setText(_translate("MainWindow", "Згенерувати:"))
        self.result.setText(_translate("MainWindow", "Результат:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
